Ordenar por nome o select de atribuir processo
jonatasrs/sei pull request #127
Opened 2020-09-24 20:02 UTC by yloliveira

Muitos usuários reclamam do fato de ser difícil encontrar um usuário na hora de atribuir um processo, caso não tenha o número do CPF.

Este PR visa melhorar um pouco a experiência destes usuários, ordenando a lista por ordem alfabética e tornando a pesquisa por nomes mais simples.

2020-09-28 23:55 UTC, jonatasrs commented
Nem todas as implementações do SEI possui este formato de atribuição com o CPF, por exemplo, em alguns órgãos poderia ser "login - Nome do Usuário", assim, deve-se corrigir esta implementação para permitir que seja configurável nas opções do complemento, permitindo que o usuário habilite quando necessário.

2020-09-28 23:57 UTC, jonatasrs requested changes
Nem todas as implementações do SEI possui este formato de atribuição com o CPF, por exemplo, em alguns órgãos poderia ser "login - Nome do Usuário", assim, deve-se corrigir esta implementação para permitir que seja configurável nas opções do complemento, permitindo que o usuário habilite quando necessário.

2020-09-29 00:02 UTC, yloliveira commented
> Nem todas as implementações do SEI possui este formato de atribuição com o CPF, por exemplo, em alguns órgãos poderia ser "login - Nome do Usuário", assim, deve-se corrigir esta implementação para permitir que seja configurável nas opções do complemento, permitindo que o usuário habilite quando necessário.

2020-09-30 20:03 UTC, yloliveira commented
@jonatasrs fiz as alterações solicitadas, aguardo novo review.

2020-10-09 22:45 UTC, jonatasrs requested changes
Existe um conflito a ser resolvido antes do merge.

2020-10-14 09:12 UTC, jonatasrs approved these changes

2020-10-14 09:12 UTC, merged